themes:
    - name: "viis"
      colors:
          - "#1A191C"
          - "#222125"
          - "#27262A"
          - "#2D2B30"
          - "#2D2B30"
          - "#333137"
          - "#3D3A41"
          - "#45434A"
          - "#4D4A52"
          - "#54515A"
          - "#5F5C66"
          - "#68656F"
          - "#74707B"
          - "#94909B"
          - "#b4b0bB"
          - "#E2E2E3"
          - "#FC808F"
          - "#FF9DB1"
          - "#FFAC72"
          - "#FFC79E"
          - "#F3E48C"
          - "#F5E8AF"
          - "#BCF092"
          - "#CFEEC2"
          - "#9BE3ED"
          - "#BBE8EE"
          - "#B4BEFE"
          - "#D6D9FC"
