theme = "default"
background_dimming = 0.7
undo_tree_history_size = 5000
icons_enabled = true

mouse = true
mouse_scroll_step_vertical = 2
mouse_scroll_step_horizontal = 2

[logging]
enabled = true
max_events = 5000

[keybindings.normal]
command = ";"

[keybindings.visual]
command = ";"

[which_key]
enabled = true
delay_ms = 2000

[zen]
width_percent = 75
show_toast = false

[[bind]]
mode = "normal"
keys = "<leader>rc"
command = ":config reload"
desc = "Reload configuration file"

[[bind]]
mode = "normal"
keys = "<leader>w"
command = ":w"
desc = "Write changes"

[[bind]]
mode = "normal"
keys = "<leader>tr"
command = ":rain"
desc = "Trigger rain"

[themes.default.ui]
"status.mode_normal" = { fg="#222125", bg="#333138" }

[themes.default.palette]
"selection_bg" = "#222024"
